### ISSUE TITLE
We need the design of handshake in our website

### ISSUE THREAD

**Issue by aakashstha** [aakashstha/ContentManagementSystem#1]
For the test purpose we had added the emoji but we must create one using the right photo editing tool.

**Comment by enish-shah** [comment]
![noto_handshake2](https://user-images.githubusercontent.com/60809016/114312025-f0670f00-9b10-11eb-96b9-42e4f0d59f08.png)
![noto_handshake](https://user-images.githubusercontent.com/60809016/114312026-f230d280-9b10-11eb-82bf-12b3f9d66b1a.png)
![noto_handshake](https://user-images.githubusercontent.com/60809016/114312029-f3fa9600-9b10-11eb-86d1-c4f087f746d0.png)
![noto_handshake2](https://user-images.githubusercontent.com/60809016/114312031-f4932c80-9b10-11eb-8761-138757657b90.png)
well I have design and please chose which every color combination you like

**Comment by enish-shah** [comment]
![noto_handshake2](https://user-images.githubusercontent.com/60809016/114312212-a03c7c80-9b11-11eb-9504-cafd19a9e6d2.png)
 I forgot this 
one

**Comment by enish-shah** [comment]
Sorry i forgot to give this one 
![second design](https://user-images.githubusercontent.com/60809016/114312384-340e4880-9b12-11eb-8f02-3a08de4e8757.png)

**Comment by aakashstha** [comment]
It's seems good but we need to match the color code in exact manner.

**Comment by enish-shah** [comment]
well in my suggestion we should select number one which I had send that would be perfect
