### ISSUE TITLE
Scrollable Cover Images

### ISSUE THREAD

**Issue by roshan2-dot** [aakashstha/ContentManagementSystem#10]
**To make a home page cover images scrollable**
*The home page cover images is very limited and not scrollable.*
Add some more images and make it scrollable.

**Comment by aakashstha** [comment]
The home page cover is not limited now there are 6 to 7 images and it is set auto horizontal  scroll after every 4 second hope its fine now. 

<img width="1440" alt="Screen Shot 2021-05-15 at 8 00 49 PM" src="https://user-images.githubusercontent.com/45267174/118364475-415a9f00-b5b8-11eb-86e2-52448c9a0333.png">
