### ISSUE TITLE
Fixing Bug in Navigation Bar

### ISSUE THREAD

**Issue by roshan2-dot** [aakashstha/ContentManagementSystem#12]
***In the navigation bar the last element "contact us" is exceeding the device screen and appearing on another side.***
**Step to reproduce:**
1. Open the application.
It appears on every page.
![Inkedbug1_LI](https://user-images.githubusercontent.com/76994144/118222170-d10c2a80-b49e-11eb-9b0c-04e669d030ff.jpg)

**Comment by enish-shah** [comment]
Bug fixed of Contact Us nav bar

**Comment by aakashstha** [comment]
The navigation bar is working fine now with all screen devices and in small screen mobile devices as well.
Thanks roshan for finding and labeling it as bug

<img width="1440" alt="Screen Shot 2021-05-15 at 7 29 10 PM" src="https://user-images.githubusercontent.com/45267174/118363456-28e88580-b5b4-11eb-97fe-9a4f59654e9f.png">
