### ISSUE TITLE
Log In Button is not working

### ISSUE THREAD

**Issue by roshan2-dot** [aakashstha/ContentManagementSystem#13]
**Admin Log In Button**
***The log in button in the admin login form is not functioning as expected. After clicking log in button it is not navigating to the admin dashboard.***
![login issue](https://user-images.githubusercontent.com/76994144/118264853-10a33880-b4d8-11eb-83fb-55c7073dbc68.png)

**Comment by enish-shah** [comment]
Admin login login bug fixed there was error in button of html code

**Comment by aakashstha** [comment]
![Uploading Screen Shot 2021-05-15 at 7.16.23 PM.png…]()

**Comment by aakashstha** [comment]
The login button is now working as expected 

<img width="1440" alt="Screen Shot 2021-05-15 at 7 17 16 PM" src="https://user-images.githubusercontent.com/45267174/118363025-2c7b0d00-b5b2-11eb-80db-f7700d656b50.png">

**Comment by aakashstha** [comment]
https://github.com/aakashstha/ContentManagementSystem/issues/13
