### ISSUE TITLE
Alignment of Social Media Icon

### ISSUE THREAD

**Issue by roshan2-dot** [aakashstha/ContentManagementSystem#14]
**Social Medias Icons In Footer**
The social media icons in the footer section are not aligned in straight line.
![social issue 1](https://user-images.githubusercontent.com/76994144/118356617-d4361200-b595-11eb-9d9c-af40f2cd7d59.png)

**Comment by enish-shah** [comment]
![3isuue solved](https://user-images.githubusercontent.com/60809016/118358358-eac87300-b56d-11eb-99eb-a871c0bf637d.png)
Issue solved
