### ISSUE TITLE
The server branch is not generating any API

### ISSUE THREAD

**Issue by aakashstha** [aakashstha/ContentManagementSystem#2]
In server branch the backend developers are supposed to work and generate API for this CMS application but till now it's not working. 
[https://github.com/aakashstha/ContentManagementSystem/tree/server](url)

**Comment by aakashstha** [comment]
[https://github.com/aakashstha/ContentManagementSystem/tree/server](url)

**Comment by anshay7** [comment]
So, as Aakash mentioned that the API for the CMS application isn't working. So, I have created a new API which works and generate effectively. You can find the link to the new API below:
https://github.com/aakashstha/ContentManagementSystem/tree/API/api/mysite
