### ISSUE TITLE
Use of icon in after completion section.

### ISSUE THREAD

**Issue by aakashstha** [aakashstha/ContentManagementSystem#4]
Because the use of emoji is not so good and it's lacking certain behavior so I remove it. So, we need some material design theme. If anybody have this idea do implement in the home page completion section.

**Comment by roshan2-dot** [comment]
**Icons on the After Completion Section**
I have added the necessary icons along with the proper .css to them.

**Comment by roshan2-dot** [comment]
I added the icons of graduation hat, book, certificate, and a user in the after completion sectioin.
