### ISSUE TITLE
Edit Handshake icon

### ISSUE THREAD

**Issue by roshan2-dot** [aakashstha/ContentManagementSystem#5]
**Handshake icon needs to be properly managed**
In the home page header section, the handshake icons and college & university & ing group icons need a proper CSS
![Screenshot 2021-04-14 094632](https://user-images.githubusercontent.com/76994144/114653286-6df47000-9d07-11eb-8d55-02995db421f1.png)
.

**Comment by enish-shah** [comment]
well this handshake icon doesn't seem attractive rather you can use something else or remove it
