### ISSUE TITLE
***Admin Dashboard Needed***

### ISSUE THREAD

**Issue by roshan2-dot** [aakashstha/ContentManagementSystem#8]
We need an admin panel dashboard to perform the CRUD operations for the courses, gallery and events.

**Comment by aakashstha** [comment]
<img width="1435" alt="admin" src="https://user-images.githubusercontent.com/45267174/118082510-081a0780-b3dd-11eb-924c-dd825f32c0e7.png">

**Comment by aakashstha** [comment]
Admin dashboard is completed now only part left is to integrate with API
