### ISSUE TITLE
Event List

### ISSUE THREAD

**Issue by roshan2-dot** [aakashstha/ContentManagementSystem#9]
***Need more events lists***
There are very few event's lists on the event page. Add more events lists.

**Comment by aakashstha** [comment]
<img width="1436" alt="Screen Shot 2021-05-13 at 11 21 43 AM" src="https://user-images.githubusercontent.com/45267174/118082744-6f37bc00-b3dd-11eb-85ee-4e7ae313f4a3.png">

**Comment by aakashstha** [comment]
whole new list of events are added I guess our CMS is satisfied now.
